name: Deploy Aquarium Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t aquarium-website .

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker stop aquarium-website || true
          docker rm aquarium-website || true
          docker rmi aquarium-website || true
          cd /home/ubuntu
          rm -rf aquarium-website || true
          git clone https://github.com/<your-username>/aquarium-website.git
          cd aquarium-website
          docker build -t aquarium-website .
          docker run -d -p 80:80 --name aquarium-website aquarium-website
